### ISSUE TITLE
Make output location relative to current folder

### ISSUE THREAD

**Issue by declercqt** [DCLukas/PoNDeR#1]
run.sh currently contains a hardcoded location for the output files. I would suggest to change this to an argument based location with an `-o` flag and a default option that is the folder where run.sh is executed.

**Comment by DCLukas** [comment]
True. Fixed in latest commit, but without flag as only one argument has to be passed

**Comment by declercqt** [comment]
1117b8d6d1885dc1d2c8ae38148c704d3f5c5850 seems to fix this indeed, thanks!
